[build]
  publish = "."

[functions]
  node_bundler = "esbuild"

# Nova sintaxe para o Python no Netlify Noble
[functions."*"]
  python_version = "3.9"

[[redirects]]
  from = "/analisar"
  to = "/.netlify/functions/analisar"
  status = 200