[build]
  publish = "."

[functions]
  python_version = "3.9"

# Esse bloco abaixo é o que resolve o "Erro de Conexão"
[[redirects]]
  from = "/analisar"
  to = "/.netlify/functions/analisar"
  status = 200
  